# server:
#     port: 8081


# spring:
#     datasource:
#         url: jdbc:postgresql://localhost:5432/microservices
#         username: postgres
#         password: root
#         driver-class-name: org.postgresql.Driver


#     jpa:
#         hibernate:
#             ddl-auto: update
#         show-sql: true 
#         property:
#             hibernate:
#                 dialect: org.hibernate.dialect.PostgreSQLDialect   

# # spring.datasource.driver-class-name=org.postgresql.Driver

# # spring.jpa.property.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect

# # spring.jpa.hibernate.ddl-auto=update

# # spring.jpa.show-sql=true

